// GENERATED BY tools/regenerate.ps1 - do not edit by hand.
// Edit js/details.json for titles/descriptions/categories, then re-run the script.
window.PORTFOLIO_VIDEOS = [
    {
        "durationSeconds":  18.8,
        "id":  "v001",
        "title":  "Reel 01",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_0286DA4D-06B6-44AD-8CC6-AA2039020D5F.mp4",
        "poster":  "thumbs/copy_0286DA4D-06B6-44AD-8CC6-AA2039020D5F.jpg",
        "resolution":  "1080x1920"
    },
    {
        "durationSeconds":  18.83,
        "id":  "v002",
        "title":  "Reel 02",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_033C1E66-6F8A-4D2D-81DE-D65626510746.mp4",
        "poster":  "thumbs/copy_033C1E66-6F8A-4D2D-81DE-D65626510746.jpg",
        "resolution":  "720x1280"
    },
    {
        "durationSeconds":  15.77,
        "id":  "v003",
        "title":  "Reel 03",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_146EBE51-82C0-4966-AD7C-CDC353FBC2F5.mp4",
        "poster":  "thumbs/copy_146EBE51-82C0-4966-AD7C-CDC353FBC2F5.jpg",
        "resolution":  "720x1280"
    },
    {
        "durationSeconds":  16.87,
        "id":  "v004",
        "title":  "Reel 04",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_3F07BD1A-486F-41AA-953C-B8CDE6DBFCA1.mp4",
        "poster":  "thumbs/copy_3F07BD1A-486F-41AA-953C-B8CDE6DBFCA1.jpg",
        "resolution":  "720x1280"
    },
    {
        "durationSeconds":  10.33,
        "id":  "v005",
        "title":  "Reel 05",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_470AFEE0-D2E2-483F-8AB5-0B6930717D13.mp4",
        "poster":  "thumbs/copy_470AFEE0-D2E2-483F-8AB5-0B6930717D13.jpg",
        "resolution":  "720x1280"
    },
    {
        "durationSeconds":  7.23,
        "id":  "v006",
        "title":  "Reel 06",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_47616138-020F-4674-B390-B02FA3F27894.mp4",
        "poster":  "thumbs/copy_47616138-020F-4674-B390-B02FA3F27894.jpg",
        "resolution":  "1080x1920"
    },
    {
        "durationSeconds":  22.8,
        "id":  "v007",
        "title":  "Reel 07",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_4A47C985-3E8A-4FC2-B318-8A6A30C7291D.mp4",
        "poster":  "thumbs/copy_4A47C985-3E8A-4FC2-B318-8A6A30C7291D.jpg",
        "resolution":  "720x1280"
    },
    {
        "durationSeconds":  22.83,
        "id":  "v008",
        "title":  "Reel 08",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_4C3E3A47-2EE2-49E1-B202-10C509A492C5.mp4",
        "poster":  "thumbs/copy_4C3E3A47-2EE2-49E1-B202-10C509A492C5.jpg",
        "resolution":  "720x1280"
    },
    {
        "durationSeconds":  15.43,
        "id":  "v009",
        "title":  "Reel 09",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_4EFCE0B8-011D-4D3C-A0B7-583BCD9694FA.mp4",
        "poster":  "thumbs/copy_4EFCE0B8-011D-4D3C-A0B7-583BCD9694FA.jpg",
        "resolution":  "720x1280"
    },
    {
        "durationSeconds":  16.9,
        "id":  "v010",
        "title":  "Reel 10",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_5EEBEB66-298C-4A26-B1D4-01A17B38802D.mp4",
        "poster":  "thumbs/copy_5EEBEB66-298C-4A26-B1D4-01A17B38802D.jpg",
        "resolution":  "720x1280"
    },
    {
        "durationSeconds":  16.43,
        "id":  "v011",
        "title":  "Reel 11",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_65108334-DB7B-41DA-B0D9-20749AB769AD.mp4",
        "poster":  "thumbs/copy_65108334-DB7B-41DA-B0D9-20749AB769AD.jpg",
        "resolution":  "720x1280"
    },
    {
        "durationSeconds":  16.43,
        "id":  "v012",
        "title":  "Reel 12",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_65A68B13-20DE-4AA4-B8C3-7D08B9D8123C.mp4",
        "poster":  "thumbs/copy_65A68B13-20DE-4AA4-B8C3-7D08B9D8123C.jpg",
        "resolution":  "720x1280"
    },
    {
        "durationSeconds":  27.9,
        "id":  "v013",
        "title":  "Reel 13",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_723BB79D-2EB0-4467-BD14-82A315FDF8D0.mp4",
        "poster":  "thumbs/copy_723BB79D-2EB0-4467-BD14-82A315FDF8D0.jpg",
        "resolution":  "720x1280"
    },
    {
        "durationSeconds":  15.17,
        "id":  "v014",
        "title":  "Reel 14",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_7ECFD7B0-552D-4E14-A263-C5EED50D8C58.mp4",
        "poster":  "thumbs/copy_7ECFD7B0-552D-4E14-A263-C5EED50D8C58.jpg",
        "resolution":  "1080x1920"
    },
    {
        "durationSeconds":  13.43,
        "id":  "v015",
        "title":  "Reel 15",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_8813F99D-FBF2-476B-8A78-7668A9340003.mp4",
        "poster":  "thumbs/copy_8813F99D-FBF2-476B-8A78-7668A9340003.jpg",
        "resolution":  "720x1280"
    },
    {
        "durationSeconds":  18.2,
        "id":  "v016",
        "title":  "Reel 16",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_9442F0B4-30A5-4D1B-947A-2C1F9C544EA1.mp4",
        "poster":  "thumbs/copy_9442F0B4-30A5-4D1B-947A-2C1F9C544EA1.jpg",
        "resolution":  "1080x1920"
    },
    {
        "durationSeconds":  10.07,
        "id":  "v017",
        "title":  "Reel 17",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_9AC7E410-E6DE-45CC-ADC4-0FCC3F345B02.mp4",
        "poster":  "thumbs/copy_9AC7E410-E6DE-45CC-ADC4-0FCC3F345B02.jpg",
        "resolution":  "720x1280"
    },
    {
        "durationSeconds":  14.67,
        "id":  "v018",
        "title":  "Reel 18",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_A2BB875F-73C1-415C-A38C-4D0103964A97.mp4",
        "poster":  "thumbs/copy_A2BB875F-73C1-415C-A38C-4D0103964A97.jpg",
        "resolution":  "1080x1920"
    },
    {
        "durationSeconds":  17.07,
        "id":  "v019",
        "title":  "Reel 19",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_AD7C77E2-9C0C-48D2-89D3-3E3347E30A35.mp4",
        "poster":  "thumbs/copy_AD7C77E2-9C0C-48D2-89D3-3E3347E30A35.jpg",
        "resolution":  "720x1280"
    },
    {
        "durationSeconds":  10.13,
        "id":  "v020",
        "title":  "Reel 20",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_B992DE6D-B5A2-4D11-94BA-FFF4692AC124.mp4",
        "poster":  "thumbs/copy_B992DE6D-B5A2-4D11-94BA-FFF4692AC124.jpg",
        "resolution":  "1080x1920"
    },
    {
        "durationSeconds":  11.93,
        "id":  "v021",
        "title":  "Reel 21",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_BB0EB4B3-92E2-4D61-AD36-84252CE40440.mp4",
        "poster":  "thumbs/copy_BB0EB4B3-92E2-4D61-AD36-84252CE40440.jpg",
        "resolution":  "720x1280"
    },
    {
        "durationSeconds":  25.03,
        "id":  "v022",
        "title":  "Reel 22",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_C095F4BC-3510-4B7B-B863-BC642EA8A864.mp4",
        "poster":  "thumbs/copy_C095F4BC-3510-4B7B-B863-BC642EA8A864.jpg",
        "resolution":  "720x1280"
    },
    {
        "durationSeconds":  11.77,
        "id":  "v023",
        "title":  "Reel 23",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_C16F10D6-5A04-43F8-BFF6-2B5D518A1B15.mp4",
        "poster":  "thumbs/copy_C16F10D6-5A04-43F8-BFF6-2B5D518A1B15.jpg",
        "resolution":  "720x1280"
    },
    {
        "durationSeconds":  16.9,
        "id":  "v024",
        "title":  "Reel 24",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_DAB6B05E-C02A-459B-A095-C91CB8C3F4A0.mp4",
        "poster":  "thumbs/copy_DAB6B05E-C02A-459B-A095-C91CB8C3F4A0.jpg",
        "resolution":  "1080x1920"
    },
    {
        "durationSeconds":  24.23,
        "id":  "v025",
        "title":  "Reel 25",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_EDA348E5-E615-4314-A455-B6F42E0381C4.mp4",
        "poster":  "thumbs/copy_EDA348E5-E615-4314-A455-B6F42E0381C4.jpg",
        "resolution":  "720x1280"
    },
    {
        "durationSeconds":  14.03,
        "id":  "v026",
        "title":  "Reel 26",
        "tags":  [
                     "product",
                     "reel"
                 ],
        "category":  "Products",
        "type":  "video",
        "description":  "Product reel for social media.",
        "order":  999,
        "src":  "videos/copy_F56869C5-50A0-4392-991B-AEDD0DDAEFEB.mp4",
        "poster":  "thumbs/copy_F56869C5-50A0-4392-991B-AEDD0DDAEFEB.jpg",
        "resolution":  "720x1280"
    }
];