/* ============================================================
   Portfolio app — renders the grid, filters and lightbox player.
   Works with js/site.js (your info) and js/data.js (your media,
   generated by tools/regenerate.ps1).
   ============================================================ */

(function () {
  "use strict";

  var site = window.PORTFOLIO_SITE || {};
  var videos = window.PORTFOLIO_VIDEOS || [];

  if (!videos.length) {
    document.getElementById("grid").innerHTML =
      '<p class="empty">No media found yet. Add files to the <code>videos/</code> or <code>images/</code> folder, then run <code>tools/regenerate.ps1</code>.</p>';
  }

  /* ---------- tiny helpers ---------- */
  function el(tag, className, text) {
    var node = document.createElement(tag);
    if (className) node.className = className;
    if (text != null) node.textContent = text;
    return node;
  }

  function fmtDuration(sec) {
    if (sec == null || isNaN(sec)) return "";
    sec = Math.round(sec);
    var m = Math.floor(sec / 60);
    var s = sec % 60;
    return m + ":" + (s < 10 ? "0" : "") + s;
  }

  function escapeHtml(str) {
    return String(str == null ? "" : str).replace(/[&<>"']/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
    });
  }

  /* ---------- state ---------- */
  var state = {
    category: "All",
    query: "",
    list: [],          // currently filtered video ids
    index: -1          // current lightbox position
  };

  var grid = document.getElementById("grid");
  var filtersEl = document.getElementById("filters");
  var searchEl = document.getElementById("search");
  var emptyEl = document.getElementById("empty");

  /* ---------- populate site info ---------- */
  function setupSite() {
    document.documentElement.style.setProperty("--accent", site.accent || "#e8546b");

    var title = site.name ? site.name + " — " + (site.role || "Portfolio") : "Portfolio";
    document.title = title;

    if (site.name) {
      document.getElementById("nav-brand").innerHTML =
        escapeHtml(site.name).replace(/ /g, "&nbsp;");
      document.getElementById("hero-title").textContent = site.name;
      document.getElementById("foot-name").textContent = site.name;
    }

    if (site.role) document.getElementById("hero-eyebrow").textContent = site.role;

    document.getElementById("year").textContent = new Date().getFullYear();
    buildContacts();
  }

  function buildContacts() {
    var wrap = document.getElementById("contact-links");
    var items = [
      { label: site.email, href: "mailto:" + site.email, ico: "✉" },
      { label: site.phone, href: "tel:" + site.phone.replace(/[^+\d]/g, ""), ico: "☏" },
      { label: "Instagram", href: site.links.instagram, ico: "◉" },
      { label: "TikTok", href: site.links.tiktok, ico: "♪" },
      { label: "YouTube", href: site.links.youtube, ico: "▶" },
      { label: "Vimeo", href: site.links.vimeo, ico: "▷" },
      { label: "LinkedIn", href: site.links.linkedin, ico: "in" },
      { label: "Behance", href: site.links.behance, ico: "B" }
    ];
    items.forEach(function (item) {
      if (!item.href) return;
      var a = document.createElement("a");
      a.className = "contact-chip";
      a.href = item.href;
      if (item.href.indexOf("http") === 0) a.target = "_blank";
      a.rel = "noopener";
      var i = el("span", "ico", item.ico);
      a.appendChild(i);
      a.appendChild(document.createTextNode(item.label));
      wrap.appendChild(a);
    });
  }

  /* ---------- categories ---------- */
  function buildFilters() {
    var cats = ["All"];
    videos.forEach(function (v) {
      if (cats.indexOf(v.category) === -1) cats.push(v.category);
    });

    cats.forEach(function (cat) {
      var b = el("button", "filter");
      b.type = "button";
      b.dataset.cat = cat;
      b.textContent = cat;
      if (cat === "All") b.classList.add("active");
      b.addEventListener("click", function () {
        state.category = cat;
        applyFilters();
      });
      filtersEl.appendChild(b);
    });
  }

  /* ---------- filtering ---------- */
  function matches(item) {
    if (state.category !== "All" && item.category !== state.category) return false;
    if (!state.query) return true;
    var q = state.query.toLowerCase();
    return (
      (item.title || "").toLowerCase().indexOf(q) > -1 ||
      (item.description || "").toLowerCase().indexOf(q) > -1 ||
      (item.tags || []).some(function (t) { return String(t).toLowerCase().indexOf(q) > -1; })
    );
  }

  function applyFilters() {
    document.querySelectorAll(".filter").forEach(function (b) {
      b.classList.toggle("active", b.dataset.cat === state.category);
    });
    state.list = videos.filter(matches).map(function (v) { return v.id; });
    render();
  }

  /* ---------- render grid ---------- */
  function render() {
    grid.innerHTML = "";
    var shown = 0;

    state.list.forEach(function (id) {
      var item = videosById[id];
      if (!item) return;
      shown++;
      grid.appendChild(card(item));
    });

    emptyEl.hidden = shown !== 0;

    if (state.index > -1) {
      state.index = state.list.indexOf(currentId);
    }
  }

  var videosById = {};
  videos.forEach(function (v, i) { v.id = v.id || "item" + i; videosById[v.id] = v; });

  function card(item) {
    var article = el("article", "card");
    article.dataset.id = item.id;
    article.setAttribute("role", "button");
    article.setAttribute("tabindex", "0");
    article.setAttribute("aria-label", "Play " + item.title);

    var media = el("div", "card-media");
    var img = document.createElement("img");
    img.loading = "lazy";
    img.alt = item.title;
    img.src = item.poster || item.src;
    img.onerror = function () {
      img.onerror = null;
      img.style.opacity = "0.12";
    };
    media.appendChild(img);

    if (item.type !== "image") {
      var play = el("div", "card-play");
      var ico = el("div", "play-ico", "▶");
      play.appendChild(ico);
      media.appendChild(play);
      if (item.durationSeconds) {
        media.appendChild(el("span", "duration", fmtDuration(item.durationSeconds)));
      }
    }

    var body = el("div", "card-body");
    body.appendChild(el("h3", "card-title", item.title));
    body.appendChild(el("p", "card-cat", item.category));

    article.appendChild(media);
    article.appendChild(body);

    var open = function () { openLightbox(item.id); };
    article.addEventListener("click", open);
    article.addEventListener("keydown", function (e) {
      if (e.key === "Enter" || e.key === " ") { e.preventDefault(); open(); }
    });

    return article;
  }

  /* ---------- lightbox ---------- */
  var lb = document.getElementById("lightbox");
  var lbMedia = document.getElementById("lb-media");
  var lbTitle = document.getElementById("lb-title");
  var lbMeta = document.getElementById("lb-meta");
  var lbDesc = document.getElementById("lb-desc");
  var lbTags = document.getElementById("lb-tags");
  var currentId = null;

  function openLightbox(id) {
    currentId = id;
    state.index = state.list.indexOf(id);
    var item = videosById[id];
    if (!item) return;

    lbMedia.innerHTML = "";
    if (item.type === "image") {
      var img = document.createElement("img");
      img.src = item.src;
      img.alt = item.title;
      lbMedia.appendChild(img);
    } else {
      var video = document.createElement("video");
      video.controls = true;
      video.playsInline = true;
      video.preload = "auto";
      video.poster = item.poster || "";
      var src = document.createElement("source");
      src.src = item.src;
      src.type = "video/mp4";
      video.appendChild(src);
      video.addEventListener("error", function () {
        if (!lbMedia.querySelector(".lb-media-err")) {
          lbMedia.appendChild(el("p", "lb-media-err", "This video could not be loaded here."));
        }
      });
      try {
        var playPromise = video.play();
        if (playPromise && typeof playPromise.catch === "function") {
          playPromise.catch(function () {});
        }
      } catch (e) {}
      lbMedia.appendChild(video);
    }

    lbTitle.textContent = item.title;
    var meta = [item.category];
    if (item.type !== "image") {
      if (item.durationSeconds) meta.unshift(fmtDuration(item.durationSeconds));
    }
    if (item.resolution) meta.push(item.resolution);
    lbMeta.textContent = meta.join("  ·  ");

    lbDesc.textContent = item.description || "";
    lbDesc.hidden = !item.description;
    lbTags.innerHTML = "";
    (item.tags || []).forEach(function (t) { lbTags.appendChild(el("span", null, t)); });

    lb.hidden = false;
    document.body.style.overflow = "hidden";
  }

  function closeLightbox() {
    lbMedia.innerHTML = "";
    lb.hidden = true;
    document.body.style.overflow = "";
    currentId = null;
  }

  function step(delta) {
    if (state.index === -1) return;
    var n = state.list.length;
    if (!n) return;
    var next = (state.index + delta + n) % n;
    openLightbox(state.list[next]);
  }

  document.getElementById("lb-close").addEventListener("click", closeLightbox);
  document.getElementById("lb-prev").addEventListener("click", function () { step(-1); });
  document.getElementById("lb-next").addEventListener("click", function () { step(1); });

  lb.addEventListener("click", function (e) {
    if (e.target === lb) closeLightbox();
  });

  document.addEventListener("keydown", function (e) {
    if (lb.hidden) return;
    if (e.key === "Escape") closeLightbox();
    else if (e.key === "ArrowLeft") step(-1);
    else if (e.key === "ArrowRight") step(1);
  });

  /* ---------- search ---------- */
  searchEl.addEventListener("input", function () {
    state.query = searchEl.value.trim();
    applyFilters();
  });

  /* ---------- nav scroll state ---------- */
  var nav = document.getElementById("nav");
  window.addEventListener("scroll", function () {
    nav.classList.toggle("scrolled", window.scrollY > 8);
  }, { passive: true });

  /* ---------- boot ---------- */
  setupSite();
  buildFilters();
  applyFilters();
})();
